server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://35.90.241.210:3306/ars
    username: root
    password: Qiongdemima!123
    driver-class-name: com.mysql.cj.jdbc.Driver
