server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ara
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
